## 1. 변수

In [84]:
# 할당 연산자 or 대입 연산자 or 치환 연산자 :   <-, ->, =

x <- 1
y <- 2
x
y

[1] 1

[1] 2

In [85]:
(x=5) 

[1] 5

In [86]:
rm(x) # 메모리에서 지우기 


In [87]:
ls() # list - 목록보기, 메모리상에 저장된(할당된) 객체의 변수 


[1] "a"         "aa"        "b"         "c"         "ch"        "d"        
 [7] "e"         "f"         "gender"    "idx"       "logical_v" "new_v"    
[13] "t_v"       "v_a"       "v_add"     "v_b"       "v_str"     "w"        
[19] "x1"        "x2"        "x3"        "xx"        "y"         "z"

## 2. Factor

In [88]:
# Factor ==> 범주형 데이터를 담기위함 
# factor(팩터로 변환할 벡터, 팩터의 범주, ordered = F)

gender = factor('m', c('m','f'))
gender

[1] m
Levels: m f

In [89]:
# 범주의 수 출력 
nlevels(gender)

[1] 2

In [90]:
# 범주 목록 출력 
levels(gender)

[1] "m" "f"

In [91]:
# 데이터 타입: mode 
mode(gender)

[1] "numeric"

In [92]:
# 객체 타입 
class(gender)

[1] "factor"

In [93]:
# 객체 정보 확인: R에서는 모든 자료형을 또는 자료구조를 객체로 취급함 
str(gender)

 Factor w/ 2 levels "m","f": 1


In [94]:
# factor의 level수정 
# 변수는 하나의 데이터를 담는다 
# 변수는 새로운 값이 들어오면 그 전에 저장된 값은 지워진다 

levels(gender)  = c('male', 'female')
gender

[1] male
Levels: male female

In [95]:
# 서열형 데이터 factor('a','c('a','b,'c'),ordered=T)
ordered(c('a','b','c'))

[1] a b c
Levels: a < b < c

In [96]:
ch = factor(c('a','b','c'),ordered = T)
ch

[1] a b c
Levels: a < b < c

## 3. 벡터(Vector)

In [97]:
# c() 함수, start:end == seq 
x1 = c(1,2,3,4)
x1

[1] 1 2 3 4

In [98]:
x2 = 1:15
x2

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

In [99]:
x3 = c('aaa','bbb','ccc','ddd') 
x3

[1] "aaa" "bbb" "ccc" "ddd"

In [100]:
ls()

[1] "a"         "aa"        "b"         "c"         "ch"        "d"        
 [7] "e"         "f"         "gender"    "idx"       "logical_v" "new_v"    
[13] "t_v"       "v_a"       "v_add"     "v_b"       "v_str"     "w"        
[19] "x1"        "x2"        "x3"        "xx"        "y"         "z"

In [101]:
y = c(x1,0,x2)
y

[1]  1  2  3  4  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

In [102]:
#append(a,b)
z = append(x1,x2)
z

[1]  1  2  3  4  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

In [103]:
# vector(length = n) 길이가 n인 벡터를 만듦 
vector(length=5) # default: FALSE 

[1] FALSE FALSE FALSE FALSE FALSE

In [104]:
c(1,3,5,c(4:6))

[1] 1 3 5 4 5 6

In [105]:
# seq(from=초기값, to=종료값, by=증가값) 초기값과 증가값이 1이면 생략 가능
seq(from=1, to=10, by=2)
seq(1,10,2)

[1] 1 3 5 7 9

[1] 1 3 5 7 9

In [106]:
seq(0,1,by=0.1) # 간격이 0.1임

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

In [107]:
seq(0,1,length.out=11) # 11개를 만듦

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

In [108]:
# rep(벡터, times=반복횟수)
rep(c(1:3),times=3)

[1] 1 2 3 1 2 3 1 2 3

In [109]:
rep(c(1:3),each=3) # each: 개별적으로 반복함 

[1] 1 1 1 2 2 2 3 3 3

In [110]:
# unique(): 중복을 제거하고 고유값을 추출하는 함수 
x = rep(c('a','b','c'),times=4)
unique(x)

[1] "a" "b" "c"

In [111]:
# v[index],[조건식], [행조건, 열조건], [행시작:행마지막, 열시작:열마지막]
# 위치값을 가지고 특정 벡터에 접근할 수 있음 
x = 1:10
x[3]
x[2:4]
x[c(1,3,5)] # 인덱스의 위치가 1,3,5인 값을 가져옴

[1] 3

[1] 2 3 4

[1] 1 3 5

In [112]:
y = c(a=1, b=3, c=7)
y[c('a','c')] # 벡터 또한 값에 이름을 지정해서 인덱스에 활용할 수 있음 

a c 
1 7

In [113]:
xx = c(1,4,8)
xx

[1] 1 4 8

In [114]:
# names(): 객체의 변수명을 읽어옴 
names(xx) = c('aaa','bbb','ccc') # 변수에 이름을 차례대로 지정할 수 있음 
xx

aaa bbb ccc 
  1   4   8

In [115]:
xx['ccc']
xx[3]
names(xx)

ccc 
  8

ccc 
  8

[1] "aaa" "bbb" "ccc"

In [116]:
aa = c(11:20)
aa[c(1,3,5,6)]

[1] 11 13 15 16

In [117]:
idx = c(1,3,5,6) # 변수를 만들어 인덱스에 활용할 수 있음 
aa[idx]
aa[c(1,3,5,6)]

[1] 11 13 15 16

[1] 11 13 15 16

In [118]:
x = c('a','b','c')
x[-1] # 1번째 요소를 제외하고 불러옴 

[1] "b" "c"

In [119]:
# 벡터의 길이: length(), NROW() - 반드시 대문자로 써야함
x = c('a','b','c')
length(x)
NROW(x)
nrow(x) # matrix의 행의 수를 추출하는 함수 

[1] 3

[1] 3

NULL

In [120]:
x = 1:10

mean(x) # 평균
range(x) # 최소, 최대값
var(x) # 분산 
sd(x) # 표준편차

[1] 5.5

[1]  1 10

[1] 9.166667

[1] 3.02765

## 4. 벡터 연산

In [121]:
# 수정 
a = c(1,2,3,4,5)
a[3] = 10 # 3번째를 10으로 변경 
a[c(2,4)]= 9 # 2, 4번째를 9로 변경 
a

[1]  1  9 10  9  5

In [122]:
# 5보다 큰 벡터의 요소의 값을 모두 3으로 변경 
a[a>5]=3
a

[1] 1 3 3 3 5

In [123]:
# 2~5번째 요소의 값을 모두 0으로 변경 
a[2:5] = 0
a

[1] 1 0 0 0 0

In [124]:
# Quiz
v_a = c(2:15)
v_a

v_a[] = 1
v_a
v_a[1:length(v_a)] = 1
v_a

[1]  2  3  4  5  6  7  8  9 10 11 12 13 14 15

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1

[1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [125]:
# 추가, c()
v_add = c(1,2,3,4,5)

In [126]:
# v_add 요소의 맨 앞에 0 추가 
v_add = c(0,v_add)
v_add

[1] 0 1 2 3 4 5

In [127]:
# v_add 요소의 뒤에 6 추가 
v_add = c(v_add, 6)
v_add

[1] 0 1 2 3 4 5 6

In [128]:
a = c(1,2,3)
b = c(4,5,6)
c = c(7,8,9)

new_v = c(a,b,c)
new_v

[1] 1 2 3 4 5 6 7 8 9

In [129]:
# append(a,b): a,b 두개의 벡터를 연결하는 함수 
# append(a,b,index): index로 b벡터의 추가 위치 지정 가능 
v_a= c('A','B','C','F','G')
v_b= c('D','E')

append(v_a,v_b,3) # v_a의 3번째 위치에 v_b 벡터룰 추가함 
v_a
v_b

[1] "A" "B" "C" "D" "E" "F" "G"

[1] "A" "B" "C" "F" "G"

[1] "D" "E"

In [130]:
# 벡터 요소 삭제: - 
t_v = 11:20 
t_v

[1] 11 12 13 14 15 16 17 18 19 20

In [131]:
# 1,3,5,6번째 요소를 제외하고 추출 
t_v[-c(1,3,5,6)]

[1] 12 14 17 18 19 20

In [132]:
# t_v의 마지막 요소를 제외하고 추출 
t_v[-length(t_v)]

[1] 11 12 13 14 15 16 17 18 19

In [133]:
# !(NOT 연산자), 논리 부정 
logical_v = c(FALSE,TRUE,TRUE,FALSE,FALSE)
logical_v
!logical_v # 반대되는 값을 얻을 수 있음 

[1] FALSE  TRUE  TRUE FALSE FALSE

[1]  TRUE FALSE FALSE  TRUE  TRUE

In [134]:
# Fancy index: 팬시 인덱스, 논리조건식을 이용한 인덱스 처리 
v_str = c('첫번째','두번째','세번째','네번째','다섯번째')
v_str

# 두번째, 세번째 요소만 추출 
v_str[c(2,3)]
v_str[2:3]

[1] "첫번째"   "두번째"   "세번째"   "네번째"   "다섯번째"

[1] "두번째" "세번째"

[1] "두번째" "세번째"

In [135]:
v_str[logical_v] # TRUE 위치에 있는 요소만 추출 

[1] "두번째" "세번째"

In [136]:
# 벡터의 사칙연산: 벡터화 연산 (요소의 개수가 배수의 형태를 띄고 있어야함) 
a = c(1,2,3,4)
b = c(5,6,7,8)

# 더하기 (각각의 요소끼리 더해짐)
c = a+b
c

# 빼기
d = a-b
d

# 곱하기 
e = a * b
e

# 나누기 
f = a / b
f 

[1]  6  8 10 12

[1] -4 -4 -4 -4

[1]  5 12 21 32

[1] 0.2000000 0.3333333 0.4285714 0.5000000

In [137]:
a = c(1,2,3,4)
b = a + 2 # 각각의 요소에 2를 더함 
b

[1] 3 4 5 6

In [138]:
a = c(1,2,3,4)
b = c(4,5)

# 경고가 발생하지만 계산은 수행됨 
a + b

[1] 5 7 7 9

In [139]:
# %in% : ~안에 포함여부를 판정하는 연산자 
'a' %in% c('a','b','c')
'd' %in% c('a','b','c')

[1] TRUE

[1] FALSE

In [140]:
# 벡터를 집합으로 취급, 집합연산자(합집합, 교집합, 차집합)
# 집합(set)은 중복을 허용하지 않는다 


# 합집합: union 
union(c('a','b','c'),c('a','d'))

# 교집합: intersect
intersect(c('a','b','c'),c('a','d'))

# 차집합: setdiff
setdiff(c('a','b','c'),c('a','d'))

[1] "a" "b" "c" "d"

[1] "a"

[1] "b" "c"

In [141]:
# 집합의 비교연산 equals
setequal(c('a','b','c'),c('a','d'))
setequal(c('a','b','c'),c('a','b','c','c'))

[1] FALSE

[1] TRUE

In [142]:
# all()- 모두, 전부, any()- 어느거 하나라도 
x = 1:10 
x

x > 5 # 각각의 요소에 비교 연산을 수행 

[1]  1  2  3  4  5  6  7  8  9 10

[1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

In [143]:
all(x>5) # 모든 것
any(x>5) # 어느 것 하나라도 

[1] FALSE

[1] TRUE

## 5. 행렬(matrix)

- matrix: 2차원 배열(행과 열로 구성)
- array: N차원 배열
- cbind(column): 열 단위로 묶음
- rbind(row): 행 단위로 묶음 

In [144]:
# matrix(벡터, 옵션): 옵션 nrow, ncol
matrix(1:12, ncol=3) 

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [145]:
matrix(1:12, ncol=3, byrow=T) # 열방향이 아닌 행방향으로 하고 싶다면 

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [146]:
matrix(1:9,c(3,3))

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [147]:
# 행렬의 행과 열에 이름을 부여할 수 있음 
# dimnames 옵션 : list타입으로 담아야함 
x = matrix(1:9, nrow=3, dimnames = list(c('item1','item2','item3'),c('data1','data2','data3')))
x

data1 data2 data3
item1 1     4     7    
item2 2     5     8    
item3 3     6     9

In [148]:
# 행렬이름[행인덱스, 열인덱스]
x[2,2]

[1] 5

In [149]:
x[1,] # 1번째 행을 추출 
x['item1',] # item1이라는 행을 추출 

data1 data2 data3 
    1     4     7

data1 data2 data3 
    1     4     7

In [150]:
x[1:2, ] # 1~2행의 데이터를 추출 
x[-3,] # 3행을 제외하고 추출 

data1 data2 data3
item1 1     4     7    
item2 2     5     8

data1 data2 data3
item1 1     4     7    
item2 2     5     8

In [151]:
x[c(1,3),c(1,3)] # 1,3번째 행과 1,3번째 열을 추출 

data1 data3
item1 1     7    
item3 3     9

In [152]:
x = matrix(1:4, nrow=2)
y = matrix(5:8, nrow=2)
x
y

x+y
x-y
x*y
x/y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 5    7   
[2,] 6    8

[,1] [,2]
[1,] 6    10  
[2,] 8    12

[,1] [,2]
[1,] -4   -4  
[2,] -4   -4

[,1] [,2]
[1,]  5   21  
[2,] 12   32

[,1]      [,2]     
[1,] 0.2000000 0.4285714
[2,] 0.3333333 0.5000000

In [153]:
# 행렬곱
x %*% y

# 전치행렬: t(),aperm()
t(x)

# 역행렬 
solve(x)

# 행렬식값 ad-bc
det(x)

[,1] [,2]
[1,] 23   31  
[2,] 34   46

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

[1] -2

In [154]:
# 행렬의 행의수와 열의 수 
nrow(x)
ncol(x)

y = matrix(1:6, ncol=3)
y

nrow(y)
ncol(y)

[1] 2

[1] 2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 2

[1] 3

## 6. Array(배열)

- 동일한 자료형으로 생성 
- N 차원 배열, 2차원이 넘어서는 배열 
- array(벡터 데이터, dim = c(행, 열, 면))

In [155]:
x = array(1:12, dim=c(3,4)) # 3행 4열 배열을 만듦 
x

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [156]:
xx = matrix(1:12, ncol=4)
xx

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [157]:
x[1, 1]

[1] 1

In [158]:
y = array(1:12, dim = c(2,2,3))
y

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

In [159]:
y[1,1,1]
y[1,2,3]
y[,,3]

[1] 1

[1] 11

[,1] [,2]
[1,]  9   11  
[2,] 10   12

In [160]:
# dim(): 배열의 차수를 추출 - 행, 열, 면
dim(y) 

[1] 2 2 3

In [161]:
# apply(행렬데이터, 방향, 연산함수) 특정 집단의 계산 
# 방향 - 1(행단위), 2(열단위)
z = array(1:12,c(3,4))
z

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [162]:
apply(z, 1, mean) # 행단위의 평균을 구함 
apply(z, 2, sum) # 열단위의 평균을 구함 

[1] 5.5 6.5 7.5

[1]  6 15 24 33

In [163]:
# sample(): 백터나 배열에서 샘플 추출하는 함수, 결과값이 백터로 반환됨
w = array(1:12, c(3,4))
w

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [164]:
sample(w) # w 배열의 모든 요소가 랜덤한 순서로 추출됨

[1]  1  8  4  7  2 10 12 11  6  3  9  5

In [165]:
sample(w,10) # 데이터의 n개 요소를 랜덤한 순서로 추출함
sample(1:45, 6)
sample(1:6, 10) # 반복을 허용하지 않음, 모집단보다 많은 표본을 추출하지 못함 
sample(1:6, 10, rep=T) # 반복을 허용함 

[1]  6  9 12  3  2  4  7 10 11  1

[1] 26 27  3  4 44 41

ERROR: Error in sample.int(length(x), size, replace, prob): 'replace = FALSE' 일때는 모집단보다 큰 샘플을 가질 수 없습니다


## 7. DataFrame(데이터프레임)

- 서로 다른 자료형을 하나로 묶는 구조 
- 표형태(table)로 데이터를 처리 
- python 의 딕셔너리(사전)의 형태, 즉 키와 값(키 = 값)

In [166]:
# data.frame(v1, v2, v3 ..., stringsAsFactor = T/F )
a = data.frame(x=c(1,2,3,4,5), y=c(2,4,6,8,10))
a

x y 
1 1  2
2 2  4
3 3  6
4 4  8
5 5 10

In [167]:
b = data.frame(x=c(1,2,3,4,5),
              y=c(2,4,6,8,10),
              z=c('M','F','M','F','M')) # 실제로 factor(c())의 형태 써야함 
str(b)

'data.frame':	5 obs. of  3 variables:
 $ x: num  1 2 3 4 5
 $ y: num  2 4 6 8 10
 $ z: Factor w/ 2 levels "F","M": 2 1 2 1 2


In [168]:
# 기존에 데이터 프레임에 새로운 열 추가 
# 파생변수 
b$v = c(3,6,9,12,15)
b

x y  z v 
1 1  2 M  3
2 2  4 F  6
3 3  6 M  9
4 4  8 F 12
5 5 10 M 15

In [169]:
df = data.frame(name=c('홍길동','이순신','장보고'),age = c(12,29,31))
str(df)
# 옵션을 주지 않아 문자열이 아닌 factor로 지정 

'data.frame':	3 obs. of  2 variables:
 $ name: Factor w/ 3 levels "이순신","장보고",..: 3 1 2
 $ age : num  12 29 31


In [170]:
df2 = data.frame(name=c('홍길동','이순신','장보고'),age = c(12,29,31), stringsAsFactors = FALSE)
str(df2)

'data.frame':	3 obs. of  2 variables:
 $ name: chr  "홍길동" "이순신" "장보고"
 $ age : num  12 29 31


In [171]:
# 데이터 프레임에 접근: 데이터프레임명$변수명 
df2$name
df2[,c('age')]
df2[,c('age'),drop=FALSE] # FALSE: 데이터 프레임 형태를 유지 

[1] "홍길동" "이순신" "장보고"

[1] 12 29 31

age
1 12 
2 29 
3 31

In [172]:
df2[-1,] # 1번째 행을 제외한 값

name   age
2 이순신 29 
3 장보고 31

In [173]:
# 데이터 프레임의 행이름, 열이름만 추출  
colnames(df2)
rownames(df2)
names(df2) # 열이름, 즉 속성만 읽어옴 

[1] "name" "age"

[1] "1" "2" "3"

[1] "name" "age"

In [174]:
# 여러 개의 벡터가 모여서 데이터 프레임이 생성됨 
name = c('홍길동','장보고','이순신','강감찬','김유신')
age = c(17,21,19,31,22)
gender=factor(c('M','F','M','F','M'))
blood.type=factor(c('A','O','B','AB','O'))

patients = data.frame(name,age,gender,blood.type)
patients

name   age gender blood.type
1 홍길동 17  M      A         
2 장보고 21  F      O         
3 이순신 19  M      B         
4 강감찬 31  F      AB        
5 김유신 22  M      O

In [176]:
# data.frame 각 요소에 접근하는 방법
# name 속성 추출
patients$name
patients[,1]

[1] 홍길동 장보고 이순신 강감찬 김유신
Levels: 강감찬 김유신 이순신 장보고 홍길동

[1] 홍길동 장보고 이순신 강감찬 김유신
Levels: 강감찬 김유신 이순신 장보고 홍길동

In [179]:
# 이순신 정보만 추출
# [인덱스], [:], [조건식], [행인덱스 ,열인덱스], [:,:]
patients[3,1]
patients[3,]

[1] 이순신
Levels: 강감찬 김유신 이순신 장보고 홍길동

name   age gender blood.type
3 이순신 19  M      B

In [183]:
patients[patients$name == '이순신', c('age', 'blood.type')]

age blood.type
3 19  B

In [190]:
# attach(속성명을 변수로 취급), detach(반대로)
head(cars, 3)

speed dist
1 4      2  
2 4     10  
3 7      4

In [191]:
str(cars)

'data.frame':	50 obs. of  2 variables:
 $ speed: num  4 4 7 7 8 9 10 10 10 11 ...
 $ dist : num  2 10 4 22 16 10 18 26 34 17 ...


In [192]:
# attach() : 속성명을 변수로 취급할 때 사용
# detach() : 해제
attach(cars)

In [193]:
speed

[1]  4  4  7  7  8  9 10 10 10 11 11 12 12 12 12 13 13 13 13 14 14 14 14 15 15
[26] 15 16 16 17 17 17 18 18 18 18 19 19 19 20 20 20 20 20 22 23 24 24 24 24 25

In [194]:
dist

[1]   2  10   4  22  16  10  18  26  34  17  28  14  20  24  28  26  34  34  46
[20]  26  36  60  80  20  26  54  32  40  32  40  50  42  56  76  84  36  46  68
[39]  32  48  52  56  64  66  54  70  92  93 120  85

In [195]:
detach(cars)

In [196]:
speed

ERROR: Error in eval(expr, envir, enclos): 객체 'speed'를 찾을 수 없습니다


In [197]:
# cars 데이터셋의 속도의 평균을 추출
mean(cars$speed)

[1] 15.4

In [198]:
attach(cars)
mean(speed)

[1] 15.4

In [199]:
# with() : 데이터 프레임에 다양한 함수를 적용할 때 열 이름을 변수치급하는 함수
# with(데이터셋, 연산함수)
with(cars, mean(speed))

[1] 15.4

In [200]:
# subset(데이터프레임, 조건, 추출할 속성) : 데이터 프레임에 일부분만 추출할 때 
# 속도가 20을 초과하는 데이터만 추출
cars[cars$speed>20,]

speed dist
44 22     66 
45 23     54 
46 24     70 
47 24     92 
48 24     93 
49 24    120 
50 25     85

In [201]:
subset(cars, speed>20)

speed dist
44 22     66 
45 23     54 
46 24     70 
47 24     92 
48 24     93 
49 24    120 
50 25     85

In [203]:
# 논리연산자 : &, | 
# 속도가 20이상 23이하 데이터 추출
cars[cars$speed >= 20 & cars$speed<=23, ]

speed dist
39 20    32  
40 20    48  
41 20    52  
42 20    56  
43 20    64  
44 22    66  
45 23    54

In [205]:
subset(cars, speed>=20 & speed<=23, c('dist'))

dist
39 32  
40 48  
41 52  
42 56  
43 64  
44 66  
45 54

In [207]:
# airquality : 공기의 질을 측정한 데이터 셋
str(airquality)

'data.frame':	153 obs. of  6 variables:
 $ Ozone  : int  41 36 12 18 NA 28 23 19 8 NA ...
 $ Solar.R: int  190 118 149 313 NA NA 299 99 19 194 ...
 $ Wind   : num  7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...
 $ Temp   : int  67 72 74 62 56 66 65 59 61 69 ...
 $ Month  : int  5 5 5 5 5 5 5 5 5 5 ...
 $ Day    : int  1 2 3 4 5 6 7 8 9 10 ...


In [208]:
head(airquality, 10)

Ozone Solar.R Wind Temp Month Day
1  41    190      7.4 67   5      1 
2  36    118      8.0 72   5      2 
3  12    149     12.6 74   5      3 
4  18    313     11.5 62   5      4 
5  NA     NA     14.3 56   5      5 
6  28     NA     14.9 66   5      6 
7  23    299      8.6 65   5      7 
8  19     99     13.8 59   5      8 
9   8     19     20.1 61   5      9 
10 NA    194      8.6 69   5     10

In [209]:
tail(airquality, 10)

Ozone Solar.R Wind Temp Month Day
144 13    238     12.6 64   9     21 
145 23     14      9.2 71   9     22 
146 36    139     10.3 81   9     23 
147  7     49     10.3 69   9     24 
148 14     20     16.6 63   9     25 
149 30    193      6.9 70   9     26 
150 NA    145     13.2 77   9     27 
151 14    191     14.3 75   9     28 
152 18    131      8.0 76   9     29 
153 20    223     11.5 68   9     30

In [211]:
# na.omit() : NA가 포함된 행을 제외하고 추출
str(na.omit(airquality))

'data.frame':	111 obs. of  6 variables:
 $ Ozone  : int  41 36 12 18 23 19 8 16 11 14 ...
 $ Solar.R: int  190 118 149 313 299 99 19 256 290 274 ...
 $ Wind   : num  7.4 8 12.6 11.5 8.6 13.8 20.1 9.7 9.2 10.9 ...
 $ Temp   : int  67 72 74 62 65 59 61 69 66 68 ...
 $ Month  : int  5 5 5 5 5 5 5 5 5 5 ...
 $ Day    : int  1 2 3 4 7 8 9 12 13 14 ...
 - attr(*, "na.action")= 'omit' Named int  5 6 10 11 25 26 27 32 33 34 ...
  ..- attr(*, "names")= chr  "5" "6" "10" "11" ...


In [213]:
mean(na.omit(airquality$Ozone))

[1] 42.12931

In [215]:
# merge : 병합, 여러 개의 데이터프레임을 할칠 때 사용한다.
name = c('홍길동','장보고','이순신','강감찬','김유신')
age = c(17,21,19,31,22)
gender=factor(c('M','F','M','F','M'))
blood.type=factor(c('A','O','B','AB','O'))

p1 = data.frame(name, age, gender)
p1

p2 = data.frame(name, blood.type)
p2

name   age gender
1 홍길동 17  M     
2 장보고 21  F     
3 이순신 19  M     
4 강감찬 31  F     
5 김유신 22  M

name   blood.type
1 홍길동 A         
2 장보고 O         
3 이순신 B         
4 강감찬 AB        
5 김유신 O

In [216]:
# merge(df1, df2, by=합칠때 키값)
p3 = merge(p1, p2, by=c('name'))

In [217]:
p3

name   age gender blood.type
1 강감찬 31  F      AB        
2 김유신 22  M      O         
3 이순신 19  M      B         
4 장보고 21  F      O         
5 홍길동 17  M      A

In [218]:
name = c('홍길동','장보고','이순신','강감찬','김유신')
name2 = c('유관순', '장고보', '강감찬', '임꺽정', '홍길동')
age = c(17,21,19,31,22)
gender=factor(c('M','F','M','F','M'))
blood.type=factor(c('A','O','B','AB','O'))

In [219]:
# 다른 이름으로 된 프레임을 병합할 때
pp1 = data.frame(name, age, gender)
pp1

pp2 = data.frame(name2, blood.type)
pp2

name   age gender
1 홍길동 17  M     
2 장보고 21  F     
3 이순신 19  M     
4 강감찬 31  F     
5 김유신 22  M

name2  blood.type
1 유관순 A         
2 장고보 O         
3 강감찬 B         
4 임꺽정 AB        
5 홍길동 O

In [221]:
# 공통인 부분만 merge
pp3 = merge(pp1, pp2, by.x='name', by.y='name2')
pp3

name   age gender blood.type
1 강감찬 31  F      B         
2 홍길동 17  M      O

In [222]:
# 다 merge
pp4 = merge(pp1, pp2, by.x='name', by.y='name2', all=TRUE)
pp4

name   age gender blood.type
1 강감찬 31  F      B         
2 김유신 22  M      NA        
3 이순신 19  M      NA        
4 장보고 21  F      NA        
5 홍길동 17  M      O         
6 유관순 NA  NA     A         
7 임꺽정 NA  NA     AB        
8 장고보 NA  NA     O